__author__ = 'Arco'
[u'1', [{u'Style': u'', u'Show': u'true', u'Type': u'table', u'Order': 1, u'Config': [
    {u'ngPattern': None, u'Name': u'\u4f9b\u5e94\u5546/\u5ba2\u6237', u'Sources': [], u'ngRequired': True, u'min': None,
     u'AttributeName': u'gongyingshangkehu', u'ngDisabled': False, u'Options': [], u'Width': u'', u'ngTrim': True,
     u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'text', u'Order': 1, u'ngMaxlength': None,
     u'Row': u''},
    {u'ngPattern': None, u'Name': u'\u5230\u6599\u65e5\u671f', u'Sources': [], u'ngRequired': True, u'min': None,
     u'AttributeName': u'daoliaoriqi', u'ngDisabled': False, u'Options': [], u'Width': u'', u'ngTrim': True,
     u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'date', u'Order': 2, u'ngMaxlength': None,
     u'Row': u''},
    {u'ngPattern': None, u'Name': u'\u5230\u6599\u603b\u6570', u'Sources': [], u'ngRequired': True, u'min': None,
     u'AttributeName': u'daoliaozongshu', u'ngDisabled': False, u'Options': [], u'Width': u'', u'ngTrim': True,
     u'ngMin': 0, u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'number', u'Order': 3,
     u'ngMaxlength': None, u'Row': u''},
    {u'ngPattern': None, u'Name': u'\u6b3e\u53f7', u'Sources': [], u'ngRequired': True, u'min': None,
     u'AttributeName': u'kuanhao', u'ngDisabled': False, u'Options': [], u'Width': u'', u'ngTrim': True, u'ngMin': 0,
     u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'text', u'Order': 4, u'ngMaxlength': None,
     u'Row': u''}, {u'ngPattern': None, u'Name': u'\u989c\u8272', u'Sources': [], u'ngRequired': True, u'min': None,
                    u'AttributeName': u'yanse', u'ngDisabled': False, u'Options': [], u'Width': u'', u'ngTrim': True,
                    u'ngMin': 0, u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'text', u'Order': 5,
                    u'ngMaxlength': None, u'Row': u''},
    {u'ngPattern': None, u'Name': u'\u8ba2\u5355\u53f7', u'Sources': [], u'ngRequired': True, u'min': None,
     u'AttributeName': u'dingdanhao', u'ngDisabled': False, u'Options': [], u'Width': u'', u'ngTrim': True, u'ngMin': 0,
     u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'text', u'Order': 6, u'ngMaxlength': None,
     u'Row': u''}, {u'ngPattern': None, u'Name': u'\u89c4\u683c', u'Sources': [], u'ngRequired': True, u'min': None,
                    u'AttributeName': u'guige', u'ngDisabled': False, u'Options': [], u'Width': u'', u'ngTrim': True,
                    u'ngMin': 0, u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'text', u'Order': 7,
                    u'ngMaxlength': None, u'Row': u''},
    {u'ngPattern': None, u'Name': u'\u6295\u4ea7\u6570', u'Sources': [], u'ngRequired': True, u'min': None,
     u'AttributeName': u'touchanshu', u'ngDisabled': False, u'Options': [], u'Width': u'', u'ngTrim': True, u'ngMin': 0,
     u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'number', u'Order': 8, u'ngMaxlength': None,
     u'Row': u''},
    {u'ngPattern': None, u'Name': u'\u8ba2\u5355\u6570', u'Sources': [], u'ngRequired': True, u'min': None,
     u'AttributeName': u'dingdanshu', u'ngDisabled': False, u'Options': [], u'Width': u'', u'ngTrim': True, u'ngMin': 0,
     u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'number', u'Order': 9, u'ngMaxlength': None,
     u'Row': u''},
    {u'ngPattern': None, u'Name': u'\u6807\u8bc6\u6570', u'Sources': [], u'ngRequired': True, u'min': None,
     u'AttributeName': u'biaoshishu', u'ngDisabled': False, u'Options': [], u'Width': u'', u'ngTrim': True, u'ngMin': 0,
     u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'number', u'Order': 10, u'ngMaxlength': None,
     u'Row': u''},
    {u'ngPattern': None, u'Name': u'\u5b9e\u6d4b\u6570', u'Sources': [], u'ngRequired': True, u'min': None,
     u'AttributeName': u'shiceshu', u'ngDisabled': False, u'Options': [], u'Width': u'', u'ngTrim': True, u'ngMin': 0,
     u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'number', u'Order': 11, u'ngMaxlength': None,
     u'Row': u''},
    {u'ngPattern': None, u'Name': u'\u5408\u683c\u6570', u'Sources': [], u'ngRequired': True, u'min': None,
     u'AttributeName': u'hegeshu', u'ngDisabled': False, u'Options': [], u'Width': u'', u'ngTrim': True, u'ngMin': 0,
     u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'number', u'Order': 12, u'ngMaxlength': None,
     u'Row': u''}, {u'ngPattern': None, u'Name': u'\u5916\u89c2', u'Sources': [], u'ngRequired': True, u'min': None,
                    u'AttributeName': u'waiguan', u'ngDisabled': False, u'Options': [], u'Width': u'', u'ngTrim': True,
                    u'ngMin': 0, u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'text', u'Order': 13,
                    u'ngMaxlength': None, u'Row': u''},
    {u'ngPattern': None, u'Name': u'\u68c0\u9a8c\u53f7', u'Sources': [], u'ngRequired': True, u'min': None,
     u'AttributeName': u'jianyanhao', u'ngDisabled': False, u'Options': [], u'Width': u'', u'ngTrim': True, u'ngMin': 0,
     u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'text', u'Order': 14, u'ngMaxlength': None,
     u'Row': u''}, {u'ngPattern': None, u'Name': u'\u5176\u4ed6', u'Sources': [], u'ngRequired': True, u'min': None,
                    u'AttributeName': u'qita', u'ngDisabled': False, u'Options': [], u'Width': u'', u'ngTrim': True,
                    u'ngMin': 0, u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'text', u'Order': 15,
                    u'ngMaxlength': None, u'Row': u''}], u'DatabaseTableName': u'RMI_FORM_DATA_B01_PN01_1_TABLE'},
        {u'Style': u'flex', u'Show': u'true', u'Type': u'map', u'Order': 2, u'Config': [
            {u'ngPattern': None, u'Name': u'\u68c0\u9a8c\u5458/\u65e5\u671f', u'Sources': [], u'ngRequired': True,
             u'min': None, u'AttributeName': u'jianyanyuanriqi', u'ngDisabled': False, u'Options': [], u'Width': u'',
             u'ngTrim': True, u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'date', u'Order': 1,
             u'ngMaxlength': None, u'Row': u'1'},
            {u'ngPattern': None, u'Name': u'\u5ba1\u6838/\u65e5\u671f', u'Sources': [], u'ngRequired': True,
             u'min': None, u'AttributeName': u'shenheriqi', u'ngDisabled': False, u'Options': [], u'Width': u'',
             u'ngTrim': True, u'max': None, u'ngMinlength': None, u'ngChange': u'', u'Type': u'date', u'Order': 2,
             u'ngMaxlength': None, u'Row': u'1'}], u'DatabaseTableName': u'RMI_FORM_DATA_B01_PN01_2_MAP'}], u'B01',
 u'1', u'1', u'PN01', u'\u8f85\u6599\u68c0\u9a8c']
