INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('商标'),'内单商标','2.1');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('商标'),'折叠商标','4');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('商标'),'款式转移印标','3');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('商标'),'LOGO标转移印标','1.5');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('商标'),'大洗标','5');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('商标'),'外销商标','10');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('商标'),'条码标','2.1');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('商标'),'电子标','0.9775');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('不干贴'),'电子不干贴','0.9775');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('不干贴'),'不干贴','0.9775');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('不干贴'),'合格证不干贴','3');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('吊牌'),'吊（单张检验）', '1.275');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('吊牌'),'吊牌','0.6885');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('吊牌'),'主吊牌','0.5');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('吊牌'),'功能吊牌','0.5');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('吊牌'),'外销吊牌','5');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('吊粒'),'吊粒','1.5');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('标识类'),'追踪唛','1.411');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('标识类'),'检验标','1.411');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('标识类'),'领标','1.411');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('标识类'),'装饰标','1.411');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('织带'),'松紧带橡根带','9');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('织带'),'肩带','9');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('织带'),'包边条','9');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('织带'),'橡根带','9');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('钢托'),'不锈钢钢托','5');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('钢托'),'尼龙包塑线材钢托','3.23');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('钢托'),'塑胶胶托','3.23');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('勾袢'),'勾 袢', '9');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('勾袢'),'四合扣','9');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('勾袢'),'前扣','9');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('勾袢'),'磁铁扣','9');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('勾袢'),'哺乳扣','9');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('勾袢'),'赠品勾袢','9');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('经编面料'),'弹力网眼','8.51');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('经编面料'),'弹力网纱','8.51');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('经编面料'),'网眼拉架','8.51');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('经编面料'),'六角网纱','8.51');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('经编面料'),'经编面料铺在桌上检验','30');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('经编面料'),'无痕切边','9');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('纬编面料'),'棉氨纶','8.51');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('纬编面料'),'纯棉紧密纺汗布','8.51');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('纬编面料'),'纯棉汗布','8.51');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('纬编面料'),'莫代尔','8.51');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('纬编面料'),'纬编面料铺在桌上检验','30');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('纬编面料'),'双面布','8.51');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('梭织面料 '),'提花色丁','8.51');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('梭织面料 '),'弹力色丁','8.51');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('梭织面料 '),'真丝素绉缎','8.51');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('梭织面料 '),'乔其纱','8.51');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('梭织面料 '),'雪纺','8.51');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('梭织面料 '),'印花真丝','8.51');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('梭织面料 '),'梭织面料铺在桌上检验','30');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('梭织面料 '),'送检','600');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('梭织面料 '),'试模压','600');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('梭织面料'),'面料对色','60');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('花边'),'电脑刺绣花边','12');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('花边'),'利维斯花边','12');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('花边'),'弹力花边','10');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('花边'),'经编花边','10');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('花边'),'弹力窄花边','10');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('花边'),'花边条','10');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('捆条'),'纱捆条','10');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('胸花'),'胸 花', '3');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('胸花'),'烫贴','0.9775');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('胸花'),'金属标','5');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('胸花'),'烫贴','9');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('胸花'),'烫石','0.9775');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('胸花'),'吊坠','4');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('调节扣'),'调节扣','2');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('纽扣'),'四眼纽扣','2');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('纽扣'),'纽扣','2');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('纽扣'),'调节扣对色','60');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('干燥剂'),'干燥剂','2');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('衬衣卡子'),'小衬衣卡子','2.5');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('衬衣卡子'),'大衬衣卡子','3');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('纸板'),'纸板','3');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('胶骨'),'胶（含每袋量规格）','30');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('鱼鳞骨'),'鱼鳞骨','6');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('拉链'),'拉链','6');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('棉绳'),'棉绳','6');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('丝带'),'丝带','6');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('涤纶肩条'),'涤纶肩条','6');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('薄膜'),'薄膜','183.872');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('百美贴'),'百美贴','183.872');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('纸箱'),'纸箱','20');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('纸箱'),'纸盒','20');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('模杯'), '模 杯', '8');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('线'),'涤棉线','15');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('线'),'低弹线','15');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('线'),'高弹线','15');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('线'),'高延伸线','15');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('线'),'钓鱼线','15');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('线'),'皮筋线','10');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('包装袋'),'包装袋','8');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('海绵'),'条绵','20');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('海绵'),'片绵','12');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('海绵'),'卷绵','200');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('白油'),'白油', '124.1425');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('油袋'),'油袋测压','25');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('油袋'),'油袋、气袋', '9');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('裁片'),'印胶裁片','8.092');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('衣架'),'衣架','6.5');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('花片'),'花片','6.5');
INSERT INTO RMI_MATERIAL_NAME(lastmodifiedtime, lastmodifieduser,MATERIALTYPEID, MATERIALNAME, WORKTIME)VALUES(getdate(), '0000',DBO.getMaterialTypeIDByMaterialTypeName('胶针'),'胶针','0.9775');

 
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('商标',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('不干贴',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('吊牌',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('吊粒',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('标识类',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('织带',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('钢托',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('勾袢',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('经编面料',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('纬编面料',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('梭织面料 ',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('花边',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('捆条',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('胸花',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('调节扣',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('纽扣',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('干燥剂',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('衬衣卡子',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('纸板',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('胶骨',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('鱼鳞骨',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('拉链',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('棉绳',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('丝带',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('涤纶肩条',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('薄膜',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('百美贴',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('纸箱',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('模杯',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('线',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('包装袋',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('海绵',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('白油',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('油袋',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('裁片',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('衣架',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('花片',getdate(),'0000');
insert into rmi_material_type(materialtypename,lastmodifiedtime,lastmodifieduser) values('胶针',getdate(),'0000');



delete from RMI_MATERIAL_TYPE;
delete from RMI_MATERIAL_NAME;
